services:
  nginx:
    container_name: nginx
    image: nginx:1.24
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.da/tls:/etc/nginx/tls
    ports:
      - 443:443
  backend:
    container_name: backend
    init: true
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ../images/user-icon:/node/images/user-icon
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "backend"}]'
    environment:
      DATADOG_ENV: "remote"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    ports:
      - 33060:3306
    volumes:
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      - ../volume/mysql:/var/lib/mysql
      - ./mysql/mysql_migration:/etc/mysql/mysql_migration
      - ./mysql/mysql.conf:/etc/mysql/conf.d/mysql.cnf
  datadog:
    container_name: datadog-agent
    image: datadog/agent:7
    pid: host
    environment:
      - DD_API_KEY=$DD_API_KEY
      - DD_SITE=ap1.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:dd-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8126:8126/tcp"
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
